insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (1, 'A', 'A1', '2421', 'Sawmills and Planing Mills, General');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (2, 'A', 'A2', '2491', 'Wood Preserving');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (3, 'A', 'A3', '2411', 'Logging');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (4, 'A', 'A4', '2426', 'Hardwood Dimension and Flooring Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (5, 'A', 'A4', '2429', 'Special Product Sawmills, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (6, 'A', 'A4', '2431', 'Millwork');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (7, 'A', 'A4', '2435', 'Hardwood Veneer and Plywood');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (8, 'A', 'A4', '2436', 'Softwood Veneer and Plywood');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (9, 'A', 'A4', '2439', 'Structural Wood Members, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (10, 'A', 'A4', '2448', 'Wood Pallets and Skids');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (11, 'A', 'A4', '2449', 'Wood Containers, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (12, 'A', 'A4', '2451', 'Mobile Homes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (13, 'A', 'A4', '2452', 'Prefabricated Wood Buildings and Components');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (14, 'A', 'A4', '2493', 'Reconstituted Wood Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (15, 'A', 'A4', '2499', 'Wood Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (16, 'A', 'A4', '2441', 'Nailed and Lock Corner Wood Boxes and Shook');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (17, 'B', 'B1', '2631', 'Paperboard Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (18, 'B', 'B2', '2611', 'Pulp Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (19, 'B', 'B2', '2621', 'Paper Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (20, 'B', 'B2', '2652', 'Setup Paperboard Boxes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (21, 'B', 'B2', '2653', 'Corrugated and Solid Fiber Boxes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (22, 'B', 'B2', '2655', 'Fiber Cans, Tubes, Drums, and Similar Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (23, 'B', 'B2', '2656', 'Sanitary Food Containers, Except Folding');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (24, 'B', 'B2', '2657', 'Folding Paperboard Boxes, Including Sanitary');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (25, 'B', 'B2', '2671', 'Packaging Paper and Plastics Film, Coated and Laminated');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (26, 'B', 'B2', '2672', 'Coated and Laminated Paper, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (27, 'B', 'B2', '2673', 'Plastics, Foil, and Coated Paper Bags');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (28, 'B', 'B2', '2674', 'Uncoated Paper and Multiwall Bags');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (29, 'B', 'B2', '2675', 'Die-Cut Paper and Paperboard and Cardboard');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (30, 'B', 'B2', '2676', 'Sanitary Paper Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (31, 'B', 'B2', '2677', 'Envelopes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (32, 'B', 'B2', '2678', 'Stationery, Tablets, and Related Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (33, 'B', 'B2', '2679', 'Converted Paper and Paperboard Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (34, 'C', 'C1', '2873', 'Nitrogenous Fertilizers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (35, 'C', 'C1', '2874', 'Phosphatic Fertilizers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (36, 'C', 'C1', '2875', 'Fertilizers, Mixing Only');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (37, 'C', 'C1', '2879', 'Pesticides and Agricultural Chemicals, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (38, 'C', 'C2', '2812', 'Alkalies and Chlorine');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (39, 'C', 'C2', '2813', 'Industrial Gases');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (40, 'C', 'C2', '2816', 'Inorganic Pigments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (41, 'C', 'C2', '2819', 'Industrial Inorganic Chemicals, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (42, 'C', 'C3', '2841', 'Soap and Other Detergents, Except Specialty Cleaners');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (43, 'C', 'C3', '2842', 'Specialty Cleaning, Polishing, and Sanitation Preparations');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (44, 'C', 'C3', '2843', 'Surface Active Agents, Finishing Agents, Sulfonated Oils, and Assistants');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (45, 'C', 'C3', '2844', 'Perfumes, Cosmetics, and Other Toilet Preparations');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (46, 'C', 'C4', '2821', 'Plastics Materials, Synthetic Resins, and Nonvulcanizable Elastomers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (47, 'C', 'C4', '2822', 'Synthetic Rubber (Vulcanizable Elastomers)');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (48, 'C', 'C4', '2823', 'Cellulosic Manmade Fibers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (49, 'C', 'C4', '2824', 'Manmade Organic Fibers, Except Cellulosic');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (50, 'C', 'C5', '2833', 'Medicinal Chemicals and Botanical Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (51, 'C', 'C5', '2834', 'Pharmaceutical Preparations');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (52, 'C', 'C5', '2835', 'In Vitro and In Vivo Diagnostic Substances');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (53, 'C', 'C5', '2836', 'Biological Products, Except Diagnostic Substances');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (54, 'C', 'C5', '2851', 'Paints, Varnishes, Lacquers, Enamels, and Allied Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (55, 'C', 'C5', '2861', 'Gum and Wood Chemicals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (56, 'C', 'C5', '2865', 'Cyclic Organic Crudes and Intermediates, and Organic Dyes and Pigments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (57, 'C', 'C5', '2869', 'Industrial Organic Chemicals, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (58, 'C', 'C5', '2891', 'Adhesives and Sealants');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (59, 'C', 'C5', '2892', 'Explosives');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (60, 'C', 'C5', '2893', 'Printing Ink');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (61, 'C', 'C5', '2895', 'Carbon Black');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (62, 'C', 'C5', '2899', 'Chemicals and Chemical Preparations, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (63, 'C', 'C5', '3952', 'Lead Pencils, Crayons, and Artists'' Materials');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (64, 'C', 'C5', '2911', 'Petroleum Refining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (65, 'D', 'D1', '2951', 'Asphalt Paving Mixtures and Blocks');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (66, 'D', 'D1', '2952', 'Asphalt Felts and Coatings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (67, 'D', 'D2', '2992', 'Lubricating Oils and Greases');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (68, 'D', 'D2', '2999', 'Products of Petroleum and Coal, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (69, 'E', 'E1', '3251', 'Brick and Structural Clay Tile');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (70, 'E', 'E1', '3253', 'Ceramic Wall and Floor Tile');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (71, 'E', 'E1', '3255', 'Clay Refractories');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (72, 'E', 'E1', '3259', 'Structural Clay Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (73, 'E', 'E1', '3261', 'Vitreous China Plumbing Fixtures and China and Earthenware Fittings and Bathroom Accessories');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (74, 'E', 'E1', '3262', 'Vitreous China Table and Kitchen Articles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (75, 'E', 'E1', '3263', 'Fine Earthenware (Whiteware) Table and Kitchen Articles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (76, 'E', 'E1', '3264', 'Porcelain Electrical Supplies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (77, 'E', 'E1', '3269', 'Pottery Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (78, 'E', 'E2', '3271', 'Concrete Block and Brick');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (79, 'E', 'E2', '3272', 'Concrete Products, Except Block and Brick');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (80, 'E', 'E2', '3273', 'Ready-Mixed Concrete');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (81, 'E', 'E2', '3274', 'Lime');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (82, 'E', 'E2', '3275', 'Gypsum Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (83, 'E', 'E3', '3211', 'Flat Glass');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (84, 'E', 'E3', '3221', 'Glass Containers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (85, 'E', 'E3', '3229', 'Pressed and Blown Glass and Glassware, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (86, 'E', 'E3', '3231', 'Glass Products, Made of Purchased Glass');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (87, 'E', 'E3', '3241', 'Cement, Hydraulic');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (88, 'E', 'E3', '3281', 'Cut Stone and Stone Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (89, 'E', 'E3', '3291', 'Abrasive Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (90, 'E', 'E3', '3292', 'Asbestos Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (91, 'E', 'E3', '3295', 'Minerals and Earths, Ground or Otherwise Treated');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (92, 'E', 'E3', '3296', 'Mineral Wool');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (93, 'E', 'E3', '3297', 'Nonclay Refractories');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (94, 'E', 'E3', '3299', 'Nonmetallic Mineral Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (95, 'F', 'F1', '3312', 'Steel Works, Blast Furnaces (Including Coke Ovens), and Rolling Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (96, 'F', 'F1', '3313', 'Electrometallurgical Products, Except Steel');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (97, 'F', 'F1', '3315', 'Steel Wiredrawing and Steel Nails and Spikes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (98, 'F', 'F1', '3316', 'Cold-Rolled Steel Sheet, Strip, and Bars');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (99, 'F', 'F1', '3317', 'Steel Pipe and Tubes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (100, 'F', 'F2', '3321', 'Gray and Ductile Iron Foundries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (101, 'F', 'F2', '3322', 'Malleable Iron Foundries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (102, 'F', 'F2', '3324', 'Steel Investment Foundries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (103, 'F', 'F2', '3325', 'Steel Foundries, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (104, 'F', 'F3', '3351', 'Rolling, Drawing, and Extruding Of Copper');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (105, 'F', 'F3', '3353', 'Aluminum Sheet, Plate, and Foil');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (106, 'F', 'F3', '3354', 'Aluminum Extruded Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (107, 'F', 'F3', '3355', 'Aluminum Rolling and Drawing, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (108, 'F', 'F3', '3356', 'Rolling, Drawing, and Extruding of Nonferrous Metals, Except Copper and Aluminum');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (109, 'F', 'F3', '3357', 'Drawing and Insulating of Nonferrous Wire');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (110, 'F', 'F4', '3363', 'Aluminum Die-Castings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (111, 'F', 'F4', '3364', 'Nonferrous Die-Castings, Except Aluminum');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (112, 'F', 'F4', '3365', 'Aluminum Foundries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (113, 'F', 'F4', '3366', 'Copper Foundries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (114, 'F', 'F4', '3369', 'Nonferrous Foundries, Except Aluminum and Copper');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (115, 'F', 'F5', '3331', 'Primary Smelting and Refining of Copper');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (116, 'F', 'F5', '3334', 'Primary Production of Aluminum');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (117, 'F', 'F5', '3339', 'Primary Smelting and Refining of Nonferrous Metals, Except Copper and Aluminum');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (118, 'F', 'F5', '3341', 'Secondary Smelting and Refining of Nonferrous Metals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (119, 'F', 'F5', '3398', 'Metal Heat Treating');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (120, 'F', 'F5', '3399', 'Primary Metal Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (121, 'G', 'G1', '1021', 'Copper Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (122, 'G', 'G2', '1011', 'Iron Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (123, 'G', 'G2', '1021', 'Copper Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (124, 'G', 'G2', '1031', 'Lead and Zinc Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (125, 'G', 'G2', '1041', 'Gold Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (126, 'G', 'G2', '1044', 'Silver Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (127, 'G', 'G2', '1061', 'Ferroalloy Ores, Except Vanadium');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (128, 'G', 'G2', '1081', 'Metal Mining Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (129, 'G', 'G2', '1094', 'Uranium-Radium-Vanadium Ores');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (130, 'G', 'G2', '1099', 'Miscellaneous Metal Ores, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (131, 'H', 'H1', '1221', 'Bituminous Coal and Lignite Surface Mining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (132, 'H', 'H1', '1222', 'Bituminous Coal Underground Mining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (133, 'H', 'H1', '1231', 'Anthracite Mining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (134, 'H', 'H1', '1241', 'Coal Mining Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (135, 'I', 'I1', '1311', 'Crude Petroleum and Natural Gas');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (136, 'I', 'I1', '1321', 'Natural Gas Liquids');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (137, 'I', 'I1', '1381', 'Drilling Oil and Gas Wells');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (138, 'I', 'I1', '1382', 'Oil and Gas Field Exploration Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (139, 'I', 'I1', '1389', 'Oil and Gas Field Services, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (140, 'J', 'J1', '1442', 'Construction Sand and Gravel');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (141, 'J', 'J1', '1446', 'Industrial Sand');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (142, 'J', 'J2', '1411', 'Dimension Stone');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (143, 'J', 'J2', '1422', 'Crushed and Broken Limestone');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (144, 'J', 'J2', '1423', 'Crushed and Broken Granite');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (145, 'J', 'J2', '1429', 'Crushed and Broken Stone, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (146, 'J', 'J2', '1481', 'Nonmetallic Minerals Services, Except Fuels');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (147, 'J', 'J2', '1499', 'Miscellaneous Nonmetallic Minerals, Except Fuels');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (148, 'J', 'J3', '1455', 'Kaolin and Ball Clay');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (149, 'J', 'J3', '1459', 'Clay, Ceramic, and Refractory Minerals, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (150, 'J', 'J3', '1474', 'Potash, Soda, and Borate Minerals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (151, 'J', 'J3', '1475', 'Phosphate Rock');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (152, 'J', 'J3', '1479', 'Chemical and Fertilizer Mineral Mining, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (153, 'M', 'M1', '5015', 'Motor Vehicle Parts, Used');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (154, 'N', 'N1', '5093', 'Scrap and Waste Materials');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (155, 'N', 'N2', '5093', 'Scrap and Waste Materials');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (156, 'P', 'P1', '4011', 'Railroads, Line-Haul Operating');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (157, 'P', 'P1', '4013', 'Railroad Switching and Terminal Establishments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (158, 'P', 'P1', '4111', 'Local and Suburban Transit');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (159, 'P', 'P1', '4119', 'Local Passenger Transportation, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (160, 'P', 'P1', '4121', 'Taxicabs');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (161, 'P', 'P1', '4131', 'Intercity and Rural Bus Transportation');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (162, 'P', 'P1', '4141', 'Local Bus Charter Service');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (163, 'P', 'P1', '4142', 'Bus Charter Service, Except Local');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (164, 'P', 'P1', '4151', 'School Buses');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (165, 'P', 'P1', '4173', 'Terminal and Service Facilities for Motor Vehicle Passenger Transportation');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (166, 'P', 'P1', '4212', 'Local Trucking Without Storage');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (167, 'P', 'P1', '4213', 'Trucking, Except Local');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (168, 'P', 'P1', '4214', 'Local Trucking With Storage');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (169, 'P', 'P1', '4215', 'Courier Services, Except by Air');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (170, 'P', 'P1', '4226', 'Special Warehousing and Storage, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (171, 'P', 'P1', '4231', 'Terminal and Joint Terminal Maintenance Facilities for Motor Freight Transportation');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (172, 'P', 'P1', '4311', 'United States Postal Service');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (173, 'P', 'P1', '5171', 'Petroleum Bulk stations and Terminals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (174, 'Q', 'Q1', '4412', 'Deep Sea Foreign Transportation of Freight');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (175, 'Q', 'Q1', '4424', 'Deep Sea Domestic Transportation of Freight');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (176, 'Q', 'Q1', '4432', 'Freight Transportation on the Great Lakes-St. Lawrence Seaway');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (177, 'Q', 'Q1', '4449', 'Water Transportation of Freight, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (178, 'Q', 'Q1', '4481', 'Deep Sea Transportation of Passengers, Except by Ferry');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (179, 'Q', 'Q1', '4482', 'Ferries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (180, 'Q', 'Q1', '4489', 'Water Transportation of Passengers, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (181, 'Q', 'Q1', '4491', 'Marine Cargo Handling');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (182, 'Q', 'Q1', '4492', 'Towing and Tugboat Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (183, 'Q', 'Q1', '4493', 'Marinas');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (184, 'Q', 'Q1', '4499', 'Water Transportation Services, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (185, 'R', 'R1', '3731', 'Ship Building and Repairing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (186, 'R', 'R1', '3732', 'Boat Building and Repairing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (187, 'S', 'S1', '4512', 'Air Transportation, Scheduled');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (188, 'S', 'S1', '4513', 'Air Courier Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (189, 'S', 'S1', '4522', 'Air Transportation, Nonscheduled');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (190, 'S', 'S1', '4581', 'Airports, Flying Fields, and Airport Terminal Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (191, 'U', 'U1', '2041', 'Flour and Other Grain Mill Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (192, 'U', 'U1', '2043', 'Cereal Breakfast Foods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (193, 'U', 'U1', '2044', 'Rice Milling');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (194, 'U', 'U1', '2045', 'Prepared Flour Mixes and Doughs');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (195, 'U', 'U1', '2046', 'Wet Corn Milling');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (196, 'U', 'U1', '2047', 'Dog and Cat Food');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (197, 'U', 'U1', '2048', 'Prepared Feed and Feed Ingredients for Animals and Fowls, Except Dogs and Cats');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (198, 'U', 'U2', '2074', 'Cottonseed Oil Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (199, 'U', 'U2', '2075', 'Soybean Oil Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (200, 'U', 'U2', '2076', 'Vegetable Oil Mills, Except Corn, Cottonseed, and Soybean');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (201, 'U', 'U2', '2077', 'Animal and Marine Fats and Oils');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (202, 'U', 'U2', '2079', 'Shortening, Table Oils, Margarine, and Other Edible Fats and Oils, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (203, 'U', 'U3', '2011', 'Meat Packing Plants');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (204, 'U', 'U3', '2013', 'Sausages and Other Prepared Meat Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (205, 'U', 'U3', '2015', 'Poultry Slaughtering and Processing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (206, 'U', 'U3', '2021', 'Creamery Butter');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (207, 'U', 'U3', '2022', 'Natural, Processed, and Imitation Cheese');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (208, 'U', 'U3', '2023', 'Dry, Condensed, and Evaporated Dairy Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (209, 'U', 'U3', '2024', 'Ice Cream and Frozen Desserts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (210, 'U', 'U3', '2026', 'Fluid Milk');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (211, 'U', 'U3', '2032', 'Canned Specialties');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (212, 'U', 'U3', '2033', 'Canned Fruits, Vegetables, Preserves, Jams, and Jellies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (213, 'U', 'U3', '2034', 'Dried and Dehydrated Fruits, Vegetables, and Soup Mixes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (214, 'U', 'U3', '2035', 'Pickled Fruits and Vegetables, Vegetable Sauces and Seasonings, and Salad Dressings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (215, 'U', 'U3', '2037', 'Frozen Fruits, Fruit Juices, and Vegetables');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (216, 'U', 'U3', '2038', 'Frozen Specialties, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (217, 'U', 'U3', '2051', 'Bread and Other Bakery Products, Except Cookies and Crackers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (218, 'U', 'U3', '2052', 'Cookies and Crackers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (219, 'U', 'U3', '2053', 'Frozen Bakery Products, Except Bread');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (220, 'U', 'U3', '2061', 'Cane Sugar, Except Refining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (221, 'U', 'U3', '2062', 'Cane Sugar Refining');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (222, 'U', 'U3', '2063', 'Beet Sugar');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (223, 'U', 'U3', '2064', 'Candy and Other Confectionery Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (224, 'U', 'U3', '2066', 'Chocolate and Cocoa Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (225, 'U', 'U3', '2067', 'Chewing Gum');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (226, 'U', 'U3', '2068', 'Salted and Roasted Nuts and Seeds');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (227, 'U', 'U3', '2082', 'Malt Beverages');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (228, 'U', 'U3', '2083', 'Malt');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (229, 'U', 'U3', '2084', 'Wines, Brandy, and Brandy Spirits');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (230, 'U', 'U3', '2085', 'Distilled and Blended Liquors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (231, 'U', 'U3', '2086', 'Bottled and Canned Soft Drinks and Carbonated Waters');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (232, 'U', 'U3', '2087', 'Flavoring Extracts and Flavoring Syrups, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (233, 'U', 'U3', '2091', 'Canned and Cured Fish and Seafoods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (234, 'U', 'U3', '2092', 'Prepared Fresh or Frozen Fish and Seafoods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (235, 'U', 'U3', '2095', 'Roasted Coffee');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (236, 'U', 'U3', '2096', 'Potato Chips, Corn Chips, and Similar Snacks');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (237, 'U', 'U3', '2097', 'Manufactured Ice');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (238, 'U', 'U3', '2098', 'Macaroni, Spaghetti, Vermicelli, and Noodles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (239, 'U', 'U3', '2099', 'Food Preparations, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (240, 'U', 'U3', '2111', 'Cigarettes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (241, 'U', 'U3', '2121', 'Cigars');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (242, 'U', 'U3', '2131', 'Chewing and Smoking Tobacco and Snuff');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (243, 'U', 'U3', '2141', 'Tobacco Stemming and Redrying');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (244, 'V', 'V1', '2211', 'Broadwoven Fabric Mills, Cotton');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (245, 'V', 'V1', '2221', 'Broadwoven Fabric Mills, Manmade Fiber and Silk');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (246, 'V', 'V1', '2231', 'Broadwoven Fabric Mills, Wool (Including Dyeing and Finishing)');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (247, 'V', 'V1', '2241', 'Narrow Fabric and Other Smallware Mills: Cotton, Wool, Silk, and Manmade Fiber');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (248, 'V', 'V1', '2251', 'Women''s Full-Length and Knee-Length Hosiery, Except Socks');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (249, 'V', 'V1', '2252', 'Hosiery, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (250, 'V', 'V1', '2253', 'Knit Outerwear Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (251, 'V', 'V1', '2254', 'Knit Underwear and Nightwear Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (252, 'V', 'V1', '2257', 'Weft Knit Fabric Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (253, 'V', 'V1', '2258', 'Lace and Warp Knit Fabric Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (254, 'V', 'V1', '2259', 'Knitting Mills, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (255, 'V', 'V1', '2261', 'Finishers of Broadwoven Fabrics of Cotton');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (256, 'V', 'V1', '2262', 'Finishers of Broadwoven Fabrics of Manmade Fiber and Silk');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (257, 'V', 'V1', '2269', 'Finishers of Textiles, Not elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (258, 'V', 'V1', '2273', 'Carpets and Rugs');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (259, 'V', 'V1', '2281', 'Yarn Spinning Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (260, 'V', 'V1', '2282', 'Yarn Texturizing, Throwing, Twisting, and Winding Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (261, 'V', 'V1', '2284', 'Thread Mills');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (262, 'V', 'V1', '2295', 'Coated Fabrics, Not Rubberized');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (263, 'V', 'V1', '2296', 'Tire Cord and Fabrics');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (264, 'V', 'V1', '2297', 'Non-woven Fabrics');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (265, 'V', 'V1', '2298', 'Cordage and Twine');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (266, 'V', 'V1', '2299', 'Textile goods, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (267, 'V', 'V1', '2311', 'Men''s and Boys'' Suits, Coats, and Overcoats');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (268, 'V', 'V1', '2321', 'Men''s and Boys'' Shirts, Except Work Shirts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (269, 'V', 'V1', '2322', 'Men''s and Boys'' Underwear and Nightwear');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (270, 'V', 'V1', '2323', 'Men''s and Boys'' Neckwear');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (271, 'V', 'V1', '2325', 'Men''s and Boys'' Separate Trousers and Slacks');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (272, 'V', 'V1', '2326', 'Men''s and Boys'' Work Clothing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (273, 'V', 'V1', '2329', 'Men''s and Boys'' Clothing, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (274, 'V', 'V1', '2331', 'Women''s, Misses'', and Juniors'' Blouses and Shirts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (275, 'V', 'V1', '2335', 'Women''s, Misses'', and Juniors'' Dresses');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (276, 'V', 'V1', '2337', 'Women''s, Misses'', and Juniors'' Suits, Skirts, and Coats');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (277, 'V', 'V1', '2339', 'Women''s, Misses'', and Juniors'' Outerwear, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (278, 'V', 'V1', '2341', 'Women''s, Misses'', Children''s, and Infants'' Underwear and Nightwear');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (279, 'V', 'V1', '2342', 'Brassieres, Girdles, and Allied Garments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (280, 'V', 'V1', '2353', 'Hats, Caps, and Millinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (281, 'V', 'V1', '2361', 'Girls'', Children''s, and Infants'' Dresses, Blouses, and Shirts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (282, 'V', 'V1', '2369', 'Girls'', Children''s, and Infants'' Outerwear, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (283, 'V', 'V1', '2371', 'Fur Goods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (284, 'V', 'V1', '2381', 'Dress and Work Gloves, Except Knit and All-Leather');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (285, 'V', 'V1', '2384', 'Robes and Dressing Gowns');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (286, 'V', 'V1', '2385', 'Waterproof Outerwear');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (287, 'V', 'V1', '2386', 'Leather and Sheep-Lined Clothing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (288, 'V', 'V1', '2387', 'Apparel belts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (289, 'V', 'V1', '2389', 'Apparel and Accessories, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (290, 'V', 'V1', '2391', 'Curtains and Draperies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (291, 'V', 'V1', '2392', 'House furnishing, Except Curtains and Draperies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (292, 'V', 'V1', '2393', 'Textile Bags');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (293, 'V', 'V1', '2394', 'Canvas and Related Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (294, 'V', 'V1', '2395', 'Pleating, Decorative and Novelty Stitching, and Tucking for the Trade');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (295, 'V', 'V1', '2396', 'Automotive Trimmings, Apparel Findings, and Related Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (296, 'V', 'V1', '2397', 'Schiffli Machine Embroideries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (297, 'V', 'V1', '2399', 'Fabricated Textile Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (298, 'V', 'V1', '3131', 'Boot and Shoe Cut Stock and Findings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (299, 'V', 'V1', '3142', 'House Slippers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (300, 'V', 'V1', '3143', 'Men''s Footwear, Except Athletic');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (301, 'V', 'V1', '3144', 'Women''s Footwear, Except Athletic');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (302, 'V', 'V1', '3149', 'Footwear, Except Rubber, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (303, 'V', 'V1', '3151', 'Leather Gloves and Mittens');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (304, 'V', 'V1', '3161', 'Luggage');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (305, 'V', 'V1', '3171', 'Women''s Handbags and Purses');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (306, 'V', 'V1', '3172', 'Personal Leather Goods, Except Women''s Handbags and Purses');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (307, 'V', 'V1', '3199', 'Leather Goods, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (308, 'W', 'W1', '2434', 'Wood Kitchen Cabinets');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (309, 'W', 'W1', '2511', 'Wood Household Furniture, Except Upholstered');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (310, 'W', 'W1', '2512', 'Wood Household Furniture, Upholstered');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (311, 'W', 'W1', '2514', 'Metal Household Furniture');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (312, 'W', 'W1', '2515', 'Mattresses, Foundations, and Convertible Beds');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (313, 'W', 'W1', '2517', 'Wood Television, Radio, Phonograph, and Sewing Machine Cabinets');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (314, 'W', 'W1', '2519', 'Household Furniture, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (315, 'W', 'W1', '2521', 'Wood Office Furniture');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (316, 'W', 'W1', '2522', 'Office Furniture, Except Wood');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (317, 'W', 'W1', '2531', 'Public Building and Related Furniture');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (318, 'W', 'W1', '2541', 'Wood Office and Store Fixtures, Partitions, Shelving, and Lockers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (319, 'W', 'W1', '2542', 'Office and Store Fixtures, Partitions, Shelving, and Lockers, Except Wood');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (320, 'W', 'W1', '2591', 'Drapery Hardware and Window Blinds and Shades');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (321, 'W', 'W1', '2599', 'Furniture and Fixtures, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (322, 'X', 'X1', '2711', 'Newspapers: Publishing, or Publishing and Printing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (323, 'X', 'X1', '2721', 'Periodicals: Publishing, or Publishing and Printing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (324, 'X', 'X1', '2731', 'Books: Publishing, or Publishing and Printing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (325, 'X', 'X1', '2732', 'Book Printing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (326, 'X', 'X1', '2741', 'Miscellaneous Publishing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (327, 'X', 'X1', '2752', 'Commercial Printing, Lithographic');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (328, 'X', 'X1', '2754', 'Commercial Printing, Gravure');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (329, 'X', 'X1', '2759', 'Commercial Printing, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (330, 'X', 'X1', '2771', 'Greeting Cards');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (331, 'X', 'X1', '2782', 'Blankbooks, Looseleaf Binders and Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (332, 'X', 'X1', '2789', 'Bookbinding and Related Work');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (333, 'X', 'X1', '2791', 'Typesetting');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (334, 'X', 'X1', '2796', 'Platemaking and Related Services');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (335, 'Y', 'Y1', '3011', 'Tires and Inner Tubes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (336, 'Y', 'Y1', '3021', 'Rubber and Plastics Footwear');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (337, 'Y', 'Y1', '3052', 'Rubber and Plastics Hose and Belting');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (338, 'Y', 'Y1', '3053', 'Gaskets, Packing, and Sealing Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (339, 'Y', 'Y1', '3061', 'Molded, Extruded, and Lathe-Cut Mechanical Rubber Goods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (340, 'Y', 'Y1', '3069', 'Fabricated Rubber Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (341, 'Y', 'Y2', '3081', 'Unsupported Plastics Film and Sheet');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (342, 'Y', 'Y2', '3082', 'Unsupported Plastics Profile Shapes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (343, 'Y', 'Y2', '3083', 'Laminated Plastics Plate, Sheet, and Profile Shapes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (344, 'Y', 'Y2', '3084', 'Plastics Pipe');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (345, 'Y', 'Y2', '3085', 'Plastics Bottles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (346, 'Y', 'Y2', '3086', 'Plastics Foam Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (347, 'Y', 'Y2', '3087', 'Custom Compounding of Purchased Plastics Resins');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (348, 'Y', 'Y2', '3088', 'Plastics Plumbing Fixtures');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (349, 'Y', 'Y2', '3089', 'Plastics Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (350, 'Y', 'Y2', '3931', 'Musical Instruments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (351, 'Y', 'Y2', '3942', 'Dolls and Stuffed Toys');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (352, 'Y', 'Y2', '3944', 'Games, Toys, and Children''s Vehicles, Except Dolls and Bicycles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (353, 'Y', 'Y2', '3949', 'Sporting and Athletic Goods, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (354, 'Y', 'Y2', '3951', 'Pens, Mechanical Pencils, and Parts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (355, 'Y', 'Y2', '3953', 'Marking Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (356, 'Y', 'Y2', '3955', 'Carbon Paper and Inked Ribbons');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (357, 'Y', 'Y2', '3961', 'Costume Jewelry and Costume Novelties, Except Precious Metal');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (358, 'Y', 'Y2', '3965', 'Fasteners, Buttons, Needles, and Pins');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (359, 'Y', 'Y2', '3991', 'Brooms and Brushes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (360, 'Y', 'Y2', '3993', 'Signs and Advertising Specialties');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (361, 'Y', 'Y2', '3995', 'Burial Caskets');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (362, 'Y', 'Y2', '3996', 'Linoleum, Asphalted-Felt-Base, and Other Hard Surface Floor Coverings, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (363, 'Y', 'Y2', '3999', 'Manufacturing Industries, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (364, 'Z', 'Z1', '3111', 'Leather Tanning and Finishing');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (365, 'AA', 'AA1', '3411', 'Metal Cans');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (366, 'AA', 'AA1', '3412', 'Metal Shipping Barrels, Drums, Kegs, and Pails');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (367, 'AA', 'AA1', '3421', 'Cutlery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (368, 'AA', 'AA1', '3423', 'Hand and Edge Tools, Except Machine Tools and Handsaws');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (369, 'AA', 'AA1', '3425', 'Saw Blades and Handsaws');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (370, 'AA', 'AA1', '3429', 'Hardware, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (371, 'AA', 'AA1', '3431', 'Enameled Iron and Metal Sanitary Ware');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (372, 'AA', 'AA1', '3432', 'Plumbing Fixture Fittings and Trim');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (373, 'AA', 'AA1', '3443', 'Fabricated Plate Work (Boiler Shops)');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (374, 'AA', 'AA1', '3444', 'Sheet Metal Work');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (375, 'AA', 'AA1', '3446', 'Architectural and Ornamental Metal Work');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (376, 'AA', 'AA1', '3448', 'Prefabricated Metal Buildings and Components');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (377, 'AA', 'AA1', '3449', 'Miscellaneous Structural Metal Work');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (378, 'AA', 'AA1', '3451', 'Screw Machine Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (379, 'AA', 'AA1', '3452', 'Bolts, Nuts, Screws, Rivets, and Washers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (380, 'AA', 'AA1', '3462', 'Iron and Steel Forgings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (381, 'AA', 'AA1', '3463', 'Nonferrous Forgings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (382, 'AA', 'AA1', '3465', 'Automotive Stampings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (383, 'AA', 'AA1', '3466', 'Crowns and Closures');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (384, 'AA', 'AA1', '3469', 'Metal Stampings, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (385, 'AA', 'AA1', '3471', 'Electroplating, Plating, Polishing, Anodizing, and Coloring');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (386, 'AA', 'AA1', '3482', 'Small Arms Ammunition');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (387, 'AA', 'AA1', '3483', 'Ammunition, Except for Small Arms');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (388, 'AA', 'AA1', '3484', 'Small Arms');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (389, 'AA', 'AA1', '3489', 'Ordnance and Accessories, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (390, 'AA', 'AA1', '3491', 'Industrial Valves');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (391, 'AA', 'AA1', '3492', 'Fluid Power Valves and Hose Fittings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (392, 'AA', 'AA1', '3493', 'Steel Springs, Except Wire');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (393, 'AA', 'AA1', '3494', 'Valves and Pipe Fittings, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (394, 'AA', 'AA1', '3495', 'Wire Springs');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (395, 'AA', 'AA1', '3496', 'Miscellaneous Fabricated Wire Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (396, 'AA', 'AA1', '3497', 'Metal Foil and Leaf');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (397, 'AA', 'AA1', '3498', 'Fabricated Pipe and Pipe Fittings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (398, 'AA', 'AA1', '3499', 'Fabricated Metal Products, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (399, 'AA', 'AA1', '3911', 'Jewelry, Precious Metal');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (400, 'AA', 'AA1', '3914', 'Silverware, Plated Ware, and Stainless Steel Ware');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (401, 'AA', 'AA1', '3915', 'Jewelers'' Findings and Materials, and Lapidary Work');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (402, 'AA', 'AA2', '3479', 'Coating, Engraving, and Allied Services, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (403, 'AB', 'AB1', '3511', 'Steam, Gas, and Hydraulic Turbines, and Turbine Generator Set Units');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (404, 'AB', 'AB1', '3519', 'Internal Combustion Engines, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (405, 'AB', 'AB1', '3523', 'Farm Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (406, 'AB', 'AB1', '3524', 'Lawn and Garden Tractors and Home Lawn and Garden Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (407, 'AB', 'AB1', '3531', 'Construction Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (408, 'AB', 'AB1', '3532', 'Mining Machinery and Equipment, Except Oil and Gas Field Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (409, 'AB', 'AB1', '3533', 'Oil and Gas Field Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (410, 'AB', 'AB1', '3534', 'Elevators and Moving Stairways');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (411, 'AB', 'AB1', '3535', 'Conveyors and Conveying Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (412, 'AB', 'AB1', '3536', 'Overhead Traveling Cranes, Hoists, and Monorail Systems');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (413, 'AB', 'AB1', '3537', 'Industrial Trucks, Tractors, Trailers, and Stackers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (414, 'AB', 'AB1', '3541', 'Machine Tools, Metal Cutting Types');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (415, 'AB', 'AB1', '3542', 'Machine Tools, Metal Forming Types');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (416, 'AB', 'AB1', '3543', 'Industrial Patterns');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (417, 'AB', 'AB1', '3544', 'Special Dies and Tools, Die Sets, Jigs and Fixtures, and Industrial Molds');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (418, 'AB', 'AB1', '3545', 'Cutting Tools, Machine Tool Accessories, and Machinists'' Precision Measuring Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (419, 'AB', 'AB1', '3546', 'Power-Driven Handtools');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (420, 'AB', 'AB1', '3547', 'Rolling Mill Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (421, 'AB', 'AB1', '3548', 'Electric and Gas Welding and Soldering Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (422, 'AB', 'AB1', '3549', 'Metalworking Machinery, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (423, 'AB', 'AB1', '3552', 'Textile Machinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (424, 'AB', 'AB1', '3553', 'Woodworking Machinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (425, 'AB', 'AB1', '3554', 'Paper Industries Machinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (426, 'AB', 'AB1', '3555', 'Printing Trades Machinery and Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (427, 'AB', 'AB1', '3556', 'Food Products Machinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (428, 'AB', 'AB1', '3559', 'Special Industry Machinery, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (429, 'AB', 'AB1', '3561', 'Pumps and Pumping Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (430, 'AB', 'AB1', '3562', 'Ball and Roller Bearings');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (431, 'AB', 'AB1', '3563', 'Air and Gas Compressors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (432, 'AB', 'AB1', '3564', 'Industrial and Commercial Fans and Blowers and Air Purification Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (433, 'AB', 'AB1', '3565', 'Packaging Machinery');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (434, 'AB', 'AB1', '3566', 'Speed Changers, Industrial High-Speed Drives, and Gears');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (435, 'AB', 'AB1', '3567', 'Industrial Process Furnaces and Ovens');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (436, 'AB', 'AB1', '3568', 'Mechanical Power Transmission Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (437, 'AB', 'AB1', '3569', 'General Industrial Machinery and Equipment, Not Elsewhere');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (438, 'AB', 'AB1', '3581', 'Automatic Vending Machines');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (439, 'AB', 'AB1', '3582', 'Commercial Laundry, Drycleaning, and Pressing Machines');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (440, 'AB', 'AB1', '3585', 'Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (441, 'AB', 'AB1', '3586', 'Measuring and Dispensing Pumps');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (442, 'AB', 'AB1', '3589', 'Service Industry Machinery, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (443, 'AB', 'AB1', '3592', 'Carburetors, Pistons, Piston Rings, and Valves');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (444, 'AB', 'AB1', '3593', 'Fluid Power Cylinders and Actuators');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (445, 'AB', 'AB1', '3594', 'Fluid Power Pumps and Motors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (446, 'AB', 'AB1', '3596', 'Scales and Balances, Except Laboratory');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (447, 'AB', 'AB1', '3599', 'Industrial and Commercial Machinery and Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (448, 'AB', 'AB1', '3711', 'Motor Vehicles and Passenger Car Bodies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (449, 'AB', 'AB1', '3713', 'Truck and Bus Bodies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (450, 'AB', 'AB1', '3714', 'Motor Vehicle Parts and Accessories');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (451, 'AB', 'AB1', '3715', 'Truck Trailers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (452, 'AB', 'AB1', '3716', 'Motor Homes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (453, 'AB', 'AB1', '3721', 'Aircraft');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (454, 'AB', 'AB1', '3724', 'Aircraft Engines and Engine Parts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (455, 'AB', 'AB1', '3728', 'Aircraft Parts and Auxiliary Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (456, 'AB', 'AB1', '3743', 'Railroad Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (457, 'AB', 'AB1', '3751', 'Motorcycles, Bicycles, and Parts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (458, 'AB', 'AB1', '3761', 'Guided Missiles and Space Vehicles');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (459, 'AB', 'AB1', '3764', 'Guided Missile and Space Vehicle Propulsion Units and Propulsion Unit Parts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (460, 'AB', 'AB1', '3769', 'Guided Missile Space Vehicle Parts and Auxiliary Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (461, 'AB', 'AB1', '3792', 'Travel Trailers and Campers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (462, 'AB', 'AB1', '3795', 'Tanks and Tank Components');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (463, 'AB', 'AB1', '3799', 'Transportation Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (464, 'AC', 'AC1', '3571', 'Electronic Computers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (465, 'AC', 'AC1', '3572', 'Computer Storage Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (466, 'AC', 'AC1', '3575', 'Computer Terminals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (467, 'AC', 'AC1', '3577', 'Computer Peripheral Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (468, 'AC', 'AC1', '3578', 'Calculating and Accounting Machines, Except Electronic Computers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (469, 'AC', 'AC1', '3579', 'Office Machines, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (470, 'AC', 'AC1', '3812', 'Search, Detection, Navigation, Guidance, Aeronautical, and Nautical Systems and Instruments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (471, 'AC', 'AC1', '3821', 'Laboratory Apparatus and Furniture');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (472, 'AC', 'AC1', '3822', 'Automatic Controls for Regulating Residential and Commercial Environments and Appliances');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (473, 'AC', 'AC1', '3823', 'Industrial Instruments for Measurement, Display, and Control of Process Variables; and Related Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (474, 'AC', 'AC1', '3824', 'Totalizing Fluid Meters and Counting Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (475, 'AC', 'AC1', '3825', 'Instruments for Measuring and Testing of Electricity and Electrical Signals');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (476, 'AC', 'AC1', '3826', 'Laboratory Analytical Instruments');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (477, 'AC', 'AC1', '3827', 'Optical Instruments and Lenses');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (478, 'AC', 'AC1', '3829', 'Measuring and Controlling Devices, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (479, 'AC', 'AC1', '3841', 'Surgical and Medical Instruments and Apparatus');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (480, 'AC', 'AC1', '3842', 'Orthopedic, Prosthetic, and Surgical Appliances and Supplies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (481, 'AC', 'AC1', '3843', 'Dental Equipment and Supplies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (482, 'AC', 'AC1', '3844', 'X-Ray Apparatus and Tubes and Related Irradiation Apparatus');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (483, 'AC', 'AC1', '3845', 'Electromedical and Electrotherapeutic Apparatus');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (484, 'AC', 'AC1', '3851', 'Ophthalmic Goods');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (485, 'AC', 'AC1', '3861', 'Photographic Equipment and Supplies');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (486, 'AC', 'AC1', '3873', 'Watches, Clocks, Clockwork Operated Devices, and Parts');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (487, 'AC', 'AC1', '3612', 'Power, Distribution, and Specialty Transformers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (488, 'AC', 'AC1', '3613', 'Switchgear and Switchboard Apparatus');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (489, 'AC', 'AC1', '3621', 'Motors and Generators');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (490, 'AC', 'AC1', '3624', 'Carbon and Graphite Products');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (491, 'AC', 'AC1', '3625', 'Relays and Industrial Controls');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (492, 'AC', 'AC1', '3629', 'Electrical Industrial Apparatus, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (493, 'AC', 'AC1', '3631', 'Household Cooking Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (494, 'AC', 'AC1', '3632', 'Household Refrigerators and HOme and Farm Freezers');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (495, 'AC', 'AC1', '3633', 'Household Laundry Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (496, 'AC', 'AC1', '3634', 'Electric Housewares and Fans');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (497, 'AC', 'AC1', '3635', 'Household Vacuum Cleaners');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (498, 'AC', 'AC1', '3639', 'Household Appliances, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (499, 'AC', 'AC1', '3641', 'Electric Lamp Bulbs and Tubes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (500, 'AC', 'AC1', '3643', 'Current-Carrying Wiring Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (501, 'AC', 'AC1', '3644', 'Noncurrent-Carrying Wiring Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (502, 'AC', 'AC1', '3645', 'Residential Electric Lighting Fixtures');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (503, 'AC', 'AC1', '3646', 'Commercial, Industrial, and Institutional Electric Lighting Fixtures');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (504, 'AC', 'AC1', '3647', 'Vehicular Lighting Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (505, 'AC', 'AC1', '3648', 'Lighting Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (506, 'AC', 'AC1', '3651', 'Household Audio and Video Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (507, 'AC', 'AC1', '3652', 'Phonograph Records and Prerecorded Audio Tapes and Disks');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (508, 'AC', 'AC1', '3661', 'Telephone and Telegraph Apparatus');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (509, 'AC', 'AC1', '3663', 'Radio and Television Broadcasting and Communications Equipment');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (510, 'AC', 'AC1', '3669', 'Communications Equipment, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (511, 'AC', 'AC1', '3671', 'Electron Tubes');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (512, 'AC', 'AC1', '3672', 'Printed Circuit Boards');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (513, 'AC', 'AC1', '3674', 'Semiconductors and Related Devices');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (514, 'AC', 'AC1', '3675', 'Electronic Capacitors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (515, 'AC', 'AC1', '3676', 'Electronic Resistors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (516, 'AC', 'AC1', '3677', 'Electronic Coils, Transformers, and Other Inductors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (517, 'AC', 'AC1', '3678', 'Electronic Connectors');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (518, 'AC', 'AC1', '3679', 'Electronic Components, Not Elsewhere Classified');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (519, 'AC', 'AC1', '3691', 'Storage Batteries');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (520, 'AC', 'AC1', '3692', 'Primary Batteries, Dry and Wet');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (521, 'AC', 'AC1', '3694', 'Electrical Equipment for Internal Combustion Engines');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (522, 'AC', 'AC1', '3695', 'Magnetic And Optical Recording Media');
insert into oeca_ref_sics (id, sector_code, subsector_code, sic_code, sic_name) values (523, 'AC', 'AC1', '3699', 'Electrical Machinery, Equipment, and Supplies, Not Elsewhere');
