insert into oeca_ref_sectors (id, sector_code, sector_name) values (1, 'A', 'TIMBER PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (2, 'B', 'PAPER AND ALLIED PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (3, 'C', 'CHEMICALS AND ALLIED PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (4, 'D', 'ASPHALT PAVING AND ROOFING MATERIALS AND LUBRICANTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (5, 'E', 'GLASS, CLAY, CEMENT, CONCRETE, AND GYPSUM PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (6, 'F', 'PRIMARY METALS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (7, 'G', 'METAL MINING (ORE MINING AND DRESSING)');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (8, 'H', 'COAL MINES AND COAL MINING-RELATED FACILITIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (9, 'I', 'OIL AND GAS EXTRACTION');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (10, 'J', 'MINERAL MINING AND DRESSING');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (11, 'K', 'HAZARDOUS WASTE TREATMENT, STORAGE, OR DISPOSAL FACILITIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (12, 'L', 'LANDFILLS, LAND APPLICATION SITES, AND OPEN DUMPS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (13, 'M', 'AUTOMOBILE SALVAGE YARDS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (14, 'N', 'SCRAP RECYCLING FACILITIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (15, 'O', 'STEAM ELECTRIC GENERATING FACILITIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (16, 'P', 'LAND TRANSPORTATION AND WAREHOUSING');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (17, 'Q', 'WATER TRANSPORTATION');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (18, 'R', 'SHIP AND BOAT BUILDING AND REPAIRING YARDS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (19, 'S', 'AIR TRANSPORTATION FACILITIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (20, 'T', 'TREATMENT WORKS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (21, 'U', 'FOOD AND KINDRED PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (22, 'V', 'TEXTILE MILLS, APPAREL, AND OTHER FABRIC PRODUCT MANUFACTURING; LEATHER AND LEATHER PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (23, 'W', 'FURNITURE AND FIXTURES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (24, 'X', 'PRINTING AND PUBLISHING');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (25, 'Y', 'RUBBER, MISCELLANEOUS PLASTIC PRODUCTS, AND MISCELLANEOUS MANUFACTURING INDUSTRIES');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (26, 'Z', 'LEATHER TANNING AND FINISHING');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (27, 'AA', 'FABRICATED METAL PRODUCTS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (28, 'AB', 'TRANSPORTATION EQUIPMENT, INDUSTRIAL OR COMMERCIAL MACHINERY');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (29, 'AC', 'ELECTRONIC, ELECTRICAL, PHOTOGRAPHIC, AND OPTICAL GOODS');
insert into oeca_ref_sectors (id, sector_code, sector_name) values (30, 'AD', 'NON-CLASSIFIED FACILITIES');


insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (1, 'A', 'A1', 'GENERAL SAWMILLS AND PLANING MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (2, 'A', 'A2', 'WOOD PRESERVING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (3, 'A', 'A3', 'LOG STORAGE AND HANDLING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (4, 'A', 'A4', 'HARDWOOD DIMENSION AND FLOORING MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (5, 'A', 'A4', 'SPECIAL PRODUCT SAWMILLS, NOT ELSEWHERE CLASSIFIED');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (6, 'A', 'A4', 'MILLWORK, VENEER, PLYWOOD, AND STRUCTURAL WOOD (SEE SECTOR W)');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (7, 'A', 'A4', 'WOOD PALLETS AND SKIDS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (8, 'A', 'A4', 'WOOD CONTAINERS, NOT ELSEWHERE CLASSIFIED');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (9, 'A', 'A4', 'WOOD BUILDINGS AND MOBILE HOMES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (10, 'A', 'A4', 'RECONSTITUTED WOOD PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (11, 'A', 'A4', 'WOOD PRODUCTS, NOT ELSEWHERE CLASSIFIED');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (12, 'A', 'A4', 'NAILED AND LOCK CORNER WOOD BOXES AND SHOOK');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (13, 'B', 'B1', 'PAPERBOARD MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (14, 'B', 'B2', 'PULP MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (15, 'B', 'B2', 'PAPER MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (16, 'B', 'B2', 'PAPERBOARD CONTAINERS AND BOXES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (17, 'B', 'B2', 'CONVERTED PAPER AND PAPERBOARD PRODUCTS, EXCEPT CONTAINERS AND BOXES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (18, 'C', 'C1', 'AGRICULTURAL CHEMICALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (19, 'C', 'C2', 'INDUSTRIAL INORGANIC CHEMICALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (20, 'C', 'C3', 'SOAPS, DETERGENTS, AND CLEANING PREPARATIONS; PERFUMES, COSMETICS, AND OTHER TOILET PREPARATIONS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (21, 'C', 'C4', 'PLASTICS MATERIALS AND SYNTHETIC RESINS, SYNTHETIC RUBBER, CELLULOSIC AND OTHER MANMADE FIBERS EXCEPT GLASS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (22, 'C', 'C5', 'MEDICINAL CHEMICALS AND BOTANICAL PRODUCTS; PHARMACEUTICAL PREPARATIONS; IN VITRO AND IN VIVO DIAGNOSTIC SUBSTANCES; AND BIOLOGICAL PRODUCTS, EXCEPT DIAGNOSTIC SUBSTANCES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (23, 'C', 'C5', 'PAINTS, VARNISHES, LACQUERS, ENAMELS, AND ALLIED PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (24, 'C', 'C5', 'INDUSTRIAL ORGANIC CHEMICALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (25, 'C', 'C5', 'MISCELLANEOUS CHEMICAL PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (26, 'C', 'C5', 'INKS AND PAINTS, INCLUDING CHINA PAINTING ENAMELS, INDIA INK, DRAWING INK, PLATINUM PAINTS FOR BURNT WOOD OR LEATHER WORK, PAINTS FOR CHINA PAINTING, ARTIST''S PAINTS AND ARTIST''S WATERCOLORS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (27, 'C', 'C5', 'PETROLEUM REFINING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (28, 'D', 'D1', 'ASPHALT PAVING AND ROOFING MATERIALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (29, 'D', 'D2', 'MISCELLANEOUS PRODUCTS OF PETROLEUM AND COAL');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (30, 'E', 'E1', 'STRUCTURAL CLAY PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (31, 'E', 'E1', 'POTTERY AND RELATED PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (32, 'E', 'E2', 'CONCRETE, GYPSUM, AND PLASTER PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (33, 'E', 'E3', 'FLAT GLASS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (34, 'E', 'E3', 'GLASS AND GLASSWARE, PRESSED OR BLOWN');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (35, 'E', 'E3', 'GLASS PRODUCTS MADE OF PURCHASED GLASS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (36, 'E', 'E3', 'HYDRAULIC CEMENT');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (37, 'E', 'E3', 'CUT STONE AND STONE PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (38, 'E', 'E3', 'ABRASIVE, ASBESTOS, AND MISCELLANEOUS NONMETALLIC MINERAL PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (39, 'F', 'F1', 'STEEL WORKS, BLAST FURNACES, AND ROLLING AND FINISHING MILLS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (40, 'F', 'F2', 'IRON AND STEEL FOUNDRIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (41, 'F', 'F3', 'ROLLING, DRAWING, AND EXTRUDING OF NONFERROUS METALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (42, 'F', 'F4', 'NONFERROUS FOUNDRIES (CASTINGS)');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (43, 'F', 'F5', 'PRIMARY SMELTING AND REFINING OF NONFERROUS METALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (44, 'F', 'F5', 'SECONDARY SMELTING AND REFINING OF NONFERROUS METALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (45, 'F', 'F5', 'MISCELLANEOUS PRIMARY METAL PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (46, 'G', 'G1', 'COPPER ORE AND MINING DRESSING FACILITIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (47, 'G', 'G2', 'IRON ORES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (48, 'G', 'G2', 'COPPER ORES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (49, 'G', 'G2', 'LEAD AND ZINC ORES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (50, 'G', 'G2', 'GOLD AND SILVER ORES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (51, 'G', 'G2', 'FERROALLOY ORES, EXCEPT VANADIUM');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (52, 'G', 'G2', 'METAL MINING SERVICES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (53, 'G', 'G2', 'MISCELLANEOUS METAL ORES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (54, 'H', 'H1', 'COAL MINES AND COAL MINING-RELATED FACILITIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (55, 'I', 'I1', 'CRUDE PETROLEUM AND NATURAL GAS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (56, 'I', 'I1', 'NATURAL GAS LIQUIDS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (57, 'I', 'I1', 'OIL AND GAS FIELD SERVICES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (58, 'J', 'J1', 'CONSTRUCTION SAND AND GRAVEL');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (59, 'J', 'J1', 'INDUSTRIAL SAND');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (60, 'J', 'J2', 'DIMENSION STONE');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (61, 'J', 'J2', 'CRUSHED AND BROKEN STONE, INCLUDING RIP RAP');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (62, 'J', 'J2', 'NONMETALLIC MINERALS SERVICES, EXCEPT FUELS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (63, 'J', 'J2', 'MISCELLANEOUS NONMETALLIC MINERALS, EXCEPT FUELS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (64, 'J', 'J3', 'CLAY, CERAMIC, AND REFRACTORY MATERIALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (65, 'J', 'J3', 'CHEMICAL AND FERTILIZER MINERAL MINING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (66, 'K', 'K1', 'HAZARDOUS WASTE TREATMENT, STORAGE, OR DISPOSAL FACILITIES, INCLUDING THOSE THAT ARE OPERATING UNDER INTERIM STATUS OR A PERMIT UNDER SUBTITLE C OF RCRA');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (67, 'L', 'L1', 'ALL LANDFILL, LAND APPLICATION SITES AND OPEN DUMPS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (68, 'L', 'L2', 'ALL LANDFILL, LAND APPLICATION SITES AND OPEN DUMPS, EXCEPT MUNICIPAL SOLID WASTE LANDFILL (MSWLF) AREAS CLOSED IN ACCORDANCE WITH 40 CFR 258.60');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (69, 'M', 'M1', 'AUTOMOBILE SALVAGE YARDS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (70, 'N', 'N1', 'SCRAP RECYCLING AND WASTE RECYCLING FACILITIES EXCEPT SOURCE-SEPARATED RECYCLING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (71, 'N', 'N2', 'SOURCE-SEPARATED RECYCLING FACILITY');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (72, 'O', 'O1', 'STEAM ELECTRIC GENERATING FACILITIES, INCLUDING COAL HANDLING SITES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (73, 'P', 'P1', 'RAILROAD TRANSPORTATION');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (74, 'P', 'P1', 'LOCAL AND HIGHWAY PASSENGER TRANSPORTATION');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (75, 'P', 'P1', 'MOTOR FREIGHT TRANSPORTATION AND WAREHOUSING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (76, 'P', 'P1', 'UNITED STATES POSTAL SERVICE');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (77, 'P', 'P1', 'PETROLEUM BULK STATIONS AND TERMINALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (81, 'Q', 'Q1', 'WATER TRANSPORTATION FACILITIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (82, 'R', 'R1', 'SHIP AND BOAT BUILDING OR REPAIRING YARDS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (83, 'S', 'S1', 'AIR TRANSPORTATION FACILITIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (84, 'T', 'T1', 'TREATMENT WORKS TREATING DOMESTIC SEWAGE, INCLUDING LAND DEDICATED TO THE DISPOSAL OF SEWAGE SLUDGE, WITH A DESIGN FLOW OF 1.0 MGD OR MORE OR REQUIRED TO HAVE A PRETREATMENT PROGRAM UNDER 40 CFR PART 403.');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (85, 'U', 'U1', 'GRAIN MILL PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (86, 'U', 'U2', 'FATS AND OILS PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (87, 'U', 'U3', 'MEAT PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (88, 'U', 'U3', 'DAIRY PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (89, 'U', 'U3', 'CANNED, FROZEN, AND PRESERVED FRUITS, VEGETABLES, AND FOOD SPECIALTIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (90, 'U', 'U3', 'BAKERY PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (91, 'U', 'U3', 'SUGAR AND CONFECTIONERY PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (92, 'U', 'U3', 'BEVERAGES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (93, 'U', 'U3', 'MISCELLANEOUS FOOD PREPARATIONS AND KINDRED PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (94, 'U', 'U3', 'TOBACCO PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (95, 'V', 'V1', 'TEXTILE MILL PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (96, 'V', 'V1', 'APPAREL AND OTHER FINISHED PRODUCTS MADE FROM FABRICS AND SIMILAR MATERIALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (97, 'V', 'V1', 'LEATHER AND LEATHER PRODUCTS (NOTE - SEE SECTOR Z1 FOR LEATHER TANNING AND FINISHING)');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (98, 'W', 'W1', 'WOOD KITCHEN CABINETS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (99, 'W', 'W1', 'FURNITURE AND FIXTURES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (100, 'X', 'X1', 'PRINTING, PUBLISHING, AND ALLIED INDUSTRIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (101, 'Y', 'Y1', 'TIRES AND INNER TUBES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (102, 'Y', 'Y1', 'RUBBER AND PLASTICS FOOTWEAR');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (103, 'Y', 'Y1', 'GASKETS, PACKING AND SEALING DEVICES, AND RUBBER AND PLASTIC HOSES AND BELTING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (104, 'Y', 'Y1', 'FABRICATED RUBBER PRODUCTS, NOT ELSEWHERE CLASSIFIED');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (105, 'Y', 'Y2', 'MISCELLANEOUS PLASTICS PRODUCTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (106, 'Y', 'Y2', 'MUSICAL INSTRUMENTS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (107, 'Y', 'Y2', 'DOLLS, TOYS, GAMES, AND SPORTING AND ATHLETIC GOODS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (108, 'Y', 'Y2', 'PENS, PENCILS, AND OTHER ARTISTS'' MATERIALS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (109, 'Y', 'Y2', 'COSTUME JEWELRY, COSTUME NOVELTIES, BUTTONS, AND MISCELLANEOUS NOTIONS, EXCEPT PRECIOUS METAL');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (110, 'Y', 'Y2', 'MISCELLANEOUS MANUFACTURING INDUSTRIES');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (111, 'Z', 'Z1', 'LEATHER TANNING AND FINISHING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (112, 'AA', 'AA1', 'FABRICATED METAL PRODUCTS, EXCEPT MACHINERY AND TRANSPORTATION EQUIPMENT, AND COATING, ENGRAVING, AND ALLIED SERVICES.');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (113, 'AA', 'AA1', 'JEWELRY, SILVERWARE, AND PLATED WARE');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (114, 'AA', 'AA2', 'FABRICATED METAL COATING AND ENGRAVING');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (115, 'AB', 'AB1', 'INDUSTRIAL AND COMMERCIAL MACHINERY, EXCEPT COMPUTER AND OFFICE EQUIPMENT (SEE SECTOR AC)');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (116, 'AB', 'AB1', 'TRANSPORTATION EQUIPMENT EXCEPT SHIP AND BOAT BUILDING AND REPAIRING (SEE SECTOR R)');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (117, 'AC', 'AC1', 'COMPUTER AND OFFICE EQUIPMENT');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (118, 'AC', 'AC1', 'MEASURING, ANALYZING, AND CONTROLLING INSTRUMENTS; PHOTOGRAPHIC AND OPTICAL GOODS, WATCHES, AND CLOCKS');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (119, 'AC', 'AC1', 'ELECTRONIC AND ELECTRICAL EQUIPMENT AND COMPONENTS, EXCEPT COMPUTER EQUIPMENT');
insert into oeca_ref_subsectors (id, sector_code, subsector_code, subsector_name) values (120, 'AD', 'AD1', 'OTHER STORMWATER DISCHARGES DESIGNATED BY THE DIRECTOR (SEE 40 CFR 122.26(A)(9)(I)(C) & (D)) OR ANY FACILITY DISCHARGING STORMWATER ASSOCIATED WITH INDUSTRIAL ACTIVITY NOT DESCRIBED BY SECTORS A-AC. NOTE - FACILITIES MAY NOT SELECT SECTOR AD. ONLY THE DIRECTOR MAY ASSIGN IT.');
