CREATE SEQUENCE  HIBERNATE_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE OECA_REF_BIA_TRIBES
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  STATE_CODE VARCHAR2(2) NOT NULL,
  TRIBE_NAME VARCHAR2(400) NOT NULL
);
CREATE INDEX IDX_BIA_TRIBES ON OECA_REF_BIA_TRIBES (STATE_CODE);

CREATE TABLE OECA_REF_CHEMICALS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  POLLUTANT_DESC VARCHAR2(4000) NOT NULL,
  SRS_ID VARCHAR2(255),
  POLLUTANT_CATEGORY_CODE VARCHAR2(255),
  CHEMICAL_FORMULA VARCHAR2(255),
  CHEMICAL_ABSTRACT_SERVICE_NMBR VARCHAR2(255),
  STATUS_FLAG VARCHAR2(1),
  SRS_SYSTEMATIC_NAME VARCHAR2(4000)
);
CREATE INDEX IDX_CHEMICALS ON OECA_REF_CHEMICALS (POLLUTANT_DESC);

CREATE TABLE OECA_REF_COUNTIES
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  STATE_CODE VARCHAR2(2) NOT NULL,
  COUNTY_NAME VARCHAR2(255) NOT NULL
);
CREATE INDEX IDX_COUNTIES ON OECA_REF_COUNTIES (STATE_CODE);

CREATE TABLE OECA_REF_POLLUTANTS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  POLLUTANT_CODE NUMBER(10) NOT NULL,
  POLLUTANT_NAME VARCHAR2(255) NOT NULL,
  POLLUTANT_SRS_NAME VARCHAR2(4000)
);
CREATE INDEX IDX_POLLUTANTS ON OECA_REF_POLLUTANTS (POLLUTANT_NAME, POLLUTANT_SRS_NAME);

CREATE TABLE OECA_REF_STATES
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  REGION_CODE VARCHAR2(2),
  STATE_CODE VARCHAR2(2) NOT NULL,
  STATE_NAME VARCHAR2(255) NOT NULL,
  STATE_USAGE VARCHAR2(1),
  STATE_FED_OPERATOR_TEXT VARCHAR2(4000)
);
CREATE UNIQUE INDEX UK_89EV33UJSVEVFLKKN07SHF8GB ON OECA_REF_STATES (STATE_CODE);
CREATE INDEX IDX_STATE_USAGE ON OECA_REF_STATES (STATE_USAGE);

CREATE TABLE OECA_REF_TRIBE_STATES
(
  TRIBAL_CODE VARCHAR2(255) NOT NULL,
  STATE_CODE VARCHAR2(2) NOT NULL
);
CREATE UNIQUE INDEX IDX_TRIBAL_STATE ON OECA_REF_TRIBE_STATES (TRIBAL_CODE, STATE_CODE);

CREATE TABLE OECA_REF_TRIBES
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  TRIBAL_CODE VARCHAR2(255) NOT NULL,
  TRIBAL_NAME VARCHAR2(255) NOT NULL
);
CREATE INDEX IDX_TRIBES ON OECA_REF_TRIBES (TRIBAL_CODE);

