CREATE TABLE OECA_REF_SECTORS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  SECTOR_CODE VARCHAR2(2) NOT NULL,
  SECTOR_NAME VARCHAR2(255) NOT NULL
);

CREATE TABLE OECA_REF_SUBSECTORS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  SECTOR_CODE VARCHAR2(2) NOT NULL,
  SUBSECTOR_CODE VARCHAR2(3) NOT NULL,
  SUBSECTOR_NAME VARCHAR2(300) NOT NULL
);
CREATE INDEX IDX_SS_SCODE ON OECA_REF_SUBSECTORS (SECTOR_CODE);

CREATE TABLE OECA_REF_SICS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  SECTOR_CODE VARCHAR2(2) NOT NULL,
  SUBSECTOR_CODE VARCHAR2(3) NOT NULL,
  SIC_CODE VARCHAR2(4) NOT NULL,
  SIC_NAME VARCHAR2(255) NOT NULL
);
CREATE INDEX IDX_SIC_SCODE ON OECA_REF_SICS (SECTOR_CODE);
CREATE INDEX IDX_SIC_SSCODE ON OECA_REF_SICS (SUBSECTOR_CODE);
