CREATE TABLE OECA_ACL_MODULE_PERMISSIONS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  ENTITY_TYPE VARCHAR2(30) NOT NULL,
  MODULE VARCHAR2(30) NOT NULL,
  PERMISSION_TYPE VARCHAR2(30) NOT NULL
);
CREATE INDEX IDX_ACL_MODULE_PERMISSIONS ON OECA_ACL_MODULE_PERMISSIONS (ENTITY_TYPE, MODULE);


CREATE TABLE OECA_ACL_USER
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  USER_ID VARCHAR2(100) NOT NULL,
  USER_DOMAIN VARCHAR2(30) NOT NULL
);
CREATE INDEX IDX_ACL_USER ON OECA_ACL_USER (USER_ID, USER_DOMAIN);


CREATE TABLE OECA_ACL_USER_PERMISSIONS
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  ENTITY_ID VARCHAR2(100) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  MODULE_PERMISSION_ID NUMBER(19) NOT NULL,
  CONSTRAINT FK_ACL_UP_REF_USER FOREIGN KEY (USER_ID) REFERENCES OECA_ACL_USER (ID),
  CONSTRAINT FK_ACL_UP_REF_MP FOREIGN KEY (MODULE_PERMISSION_ID) REFERENCES OECA_ACL_MODULE_PERMISSIONS (ID)
);


CREATE TABLE OECA_ACL_USER_PERMISSIONS_REQ
(
  ID NUMBER(19) PRIMARY KEY NOT NULL,
  ENTITY_ID VARCHAR2(100) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  MODULE_PERMISSION_ID NUMBER(19) NOT NULL,
  REQUEST_STATUS VARCHAR2(30) NOT NULL,
  REQUEST_ACTION VARCHAR2(30) NOT NULL,
  REQUESTER_USER_ID NUMBER(19) NOT NULL,
  REQUEST_DATE TIMESTAMP NOT NULL,
  REVIEWER_USER_ID NUMBER(19),
  REVIEW_DATE TIMESTAMP,
  REVIEW_COMMENT VARCHAR2(4000),
  CONSTRAINT FK_ACL_UPR_REF_USER FOREIGN KEY (USER_ID) REFERENCES OECA_ACL_USER (ID),
  CONSTRAINT FK_ACL_UPR_REF_MP FOREIGN KEY (MODULE_PERMISSION_ID) REFERENCES OECA_ACL_MODULE_PERMISSIONS (ID)
);
